[package]
name = "gsm"
version = "0.4.0"
authors = ["David Huseby"]
edition = "2018"
description = "A very simple generic stack machine crate"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/dhuseby/gsm"

[dependencies]
